config/routes.rb
Beaver::Application.routes.draw do
  get "sessions/new"
  root 'pages#home'
  get "pages/about"
  resources :posts
  get "login" => "sessions#new", :as => "login"
  resources :sessions

  

end

app/models/post.rb
class Post < ActiveRecord::Base
end
=begin
require 'rubygems'
require 'redcarpet'
class Post < ActiveRecord::Base
	before_save :render_body

	private
	def render_body
		
		#renderer = Redcarpet::Render::HTML.new
		renderer = PygmentizeHTML
		extensions = {fenced_code_blocks: true}
		redcarpet = Redcarpet::Markdown.new(renderer, extensions)
		self.description = redcarpet.render self.description		
	end
end

class PygmentizeHTML < Redcarpet::Render::HTML
	def block_code(code, language)
		require 'pygmentize'
		Pygmentize.process(code, language)
	end
end
=end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :admin?
  helper_method :current_user

  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end 

  def admin?
	if current_user.nil?
		false
	else
		current_user.admin
	end
  end

  def authorize
	unless admin?
		flash[:error]="Unauthorized access"
		redirect_to root_path
		false
	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :summary,  :description, :publish)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new  
  end  
    
  def create  
    user = User.find_by(username: params[:username]).try(:authenticate, params[:password]) 
    #user = User.authenticate(params[:email], params[:password])  
    if user  
      session[:user_id] = user.id  
      redirect_to root_url, :notice => "Logged in!"  
    else  
      flash.now.alert = "Invalid email or password"  
      render "new"  
    end  
  end  

  def destroy
      session[:user_id] = nil  
      redirect_to root_url, :notice => "Logged Out" 
  end
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end
	def create
		@user=User.new(params[:user])
		if @user.save  
		      redirect_to root_url, :notice => "Signed up!"  
		else  
		      render "new" 	
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
=begin
	require 'rubygems'
	require 'redcarpet'
	class PygmentizeHTML < Redcarpet::Render::HTML
		def block_code(code, language)
			require 'pygmentize'
			require 'pygments.rb'
			#Pygmentize.process(code, language)
			Pygments.highlight(code, :lexer => language)
		end
	end
=end

	def markdown(text)
		renderer=Redcarpet::Render::HTML.new(prettify: true)
		extensions={ fenced_code_blocks: true }
		#renderer2=PygmentizeHTML
		Redcarpet::Markdown.new(renderer, extensions).render text	
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head profile="http://www.w3.org/2005/10/profile">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wheel N' Axle" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
<link href="http://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Allerta" rel="stylesheet" type="text/css">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


  </head>
  <body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=150980305103487";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
    <%= content_for?(:blog_scripts) ? yield(:blog_scripts) : "" %>
    <div class="navbar navbar-fixed-top navbar-inverse allerta-font">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Wheel N' Axle", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
<li class="divider-vertical"></li>
              <li><%= link_to "Home", root_path  %></li>
<li class="divider-vertical"></li>
              <li><%= link_to "Blog", posts_path  %></li>
<!--
<li class="divider-vertical"></li><li>
              <%# link_to "About Us", pages_about_path  %>
</li>
-->
<li class="divider-vertical"></li>
	      <% if admin? %>
              <li><%= button_to "Sign Out", session_path(session[:user_id]), {method: :delete , class: "btn"}  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container crimson-font">
	<%= yield %>

      <footer class="row span12">      
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="row aboutbox">
<div class="span2 pull-left">
<%= image_tag "myself-300.jpg", { :class => "img-polaroid" }%>
</div>
<div class="allerta-font font20 span8">
      <p>Surya worked as a QA engineer for three years. Having played around with stuff others built, he wants to build his own stuff now. He wants to build things that solve problems. </p>

</div>
</div>
<div class="row aboutbox">
<div class="span2 pull-left">
<%= image_tag "sridhar-scaled.jpg", { :class => "img-polaroid" }%>
</div>
<div class="allerta-font font20 span8">
      <p>Business runs in Sridhar's blood.  He too is passionate about building technology that makes our lives easier.  </p>
</div>
</div>

<div class="row aboutbox">
<div class="span2 pull-left">
<%= image_tag "rishi-scaled.jpg", { :class => "img-polaroid" }%>
</div>
<div class="allerta-font font20 span8">
      <p>Rishi Hari will be marketing our products to the world</p>
</div>
</div>

app/views/pages/home.html.erb
<div class="row">
<div id="banner"></div>
</div>

<div class="row">
	<div class="span10 offset1 allerta-headline letterpress">Some problems deserve to be solved.</div>
</div>
<div class="row">
	<div class="span3 offset9 allerta-headline2 letterpress">So we try...</div>
</div>
<div id="mission">
	<div class="row">
		<div class="span7 offset3 allerta-headline3">
		We are cooking something spicy. Give us just a few more days.
		</div>
	</div>
	<div id="progress" class="row">
		<div class="span4 offset4">
		
			<div class="progress progress-success progress-striped active">
				  <div class="bar" style="width: 50%"></div>
			</div>
		</div>	
	</div>
	<div class="row">
		<div class="span7 offset3  allerta-headline3">
		Meanwhile a few starters to trigger your appetite. Follow us via
		</div>
	</div>
</div>
<div id="followBox">
	<div class="row">
		<div class="span2 offset4 allerta-headline3">
			<a href="./posts"><i class="icon-comment icon-4x"></i></a><p>
			<%= link_to "Our Blog", posts_path %></p>
		</div>
		<div class="span5 allerta-headline3 ">
			<a href="https://www.facebook.com/pages/Wheelnaxle/150562401806874"><i class="icon-facebook-sign icon-4x"></i></a><p><a href="https://www.facebook.com/pages/Wheelnaxle/150562401806874">Our FB page</a></p><div class="fb-like" data-href="https://www.facebook.com/pages/Wheelnaxle/150562401806874" data-width="450" data-layout="button_count" data-show-faces="false" data-send="true"></div>
		</div>
	</div>
</div>

app/views/posts/_disqus.html.erb
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'wheelnaxle'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
    

app/views/posts/_fbcomments.html.erb
<div class="fb-comments" data-href="http://wheelnaxle.com" data-width="700" data-num-posts="10"></div>

app/views/posts/_fbjsinclude.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/posts/_fblike.html.erb
<div class="fb-like" data-href="http://www.wheelnaxle.com" data-send="true" data-width="450" data-show-faces="true"></div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-vertical row span12' } do |f| %>
  <%= f.input :title %>
 <%= f.input :summary, as: :text , input_html: { class: "post-summary row span12"} %>
  <%= f.input :description, as: :text , input_html: { class: "post-description row span12"} %>
  <%= f.input :publish %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/_scripts.html.erb
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
<script type="text/x-mathjax-config">
	MathJax.Hub.Config({       
    	"HTML-CSS": { scale: 200}    
  	});   
</script>
<%= javascript_include_tag  "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" %>
<script type="text/javascript">
MathJax.Hub.Queue(["Typeset",MathJax.Hub]); 
</script> 

app/views/posts/_tweet.html.erb
<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<% content_for :blog_scripts do %>
 <%= render partial: 'scripts' %>
<% end %>

<% @posts.sort_by { |post| post.created_at }.reverse.each do |post| %>
	<% if post.publish or admin? %>
		<div class="row"><div id="post-title" class="span12"><%= post.title %></div></div>
		<div class="row"><div class="span12 font20">
		<% if post.summary.nil? %>
		 	<%= raw markdown post.description %>
		<% else %>
		 	<%= raw markdown post.summary %>
		<% end %>
		</div></div>
		<div class="row"><div class="span12 font11"><%= link_to "Read more", post_path(post.id), {class: "btn btn-info" } %></div></div>
		<hr width=100%> 
	<% end %>
<% end %>

<% if admin? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/posts/index2.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<% content_for :blog_scripts do %>
 <%= render partial: 'scripts' %>
 <%= render partial: 'fbjsinclude' %>
<% end %>  
<div class="row"> 
	<div class="span12 font20">
	  <h1><%= @post.title %></h1>
	</div>
</div>

<div class="row"> 
<hr width=100%>
</div>
<div class="row"> 
	<div class="row span12 font20">
	<%= raw markdown @post.description %>
	</div>
</div>

<div class="row"> 
<hr width=100%>
</div>
<div class="row"> 
	<div class="span6">
	<%= render partial: 'fblike' %>
	</div>
	<div class="span6">
	<%= render partial: 'tweet' %>
	</div>
</div> 
<div class="row"> 
<hr width=100%>
</div>

<div class="row">
	<div class="span12">
	<h2>Comments:</h2>
	<%= render partial: 'fbcomments' %>
	</div>
</div>
<% if admin? %>
<div class="row span12 form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% end %>